### ISSUE TITLE
How do I show my webmentions?

### ISSUE THREAD

**Issue by frankmeeuwsen** [aarongustafson/jekyll-webmention_io#117]
I've succesfully implemented the gem and included the code from the quickstart guide to my testblog (https://ecstatic-jang-1b098a.netlify.com). I've succesfully sent a webmention from the webmention.rocks testsuite to [a post](https://ecstatic-jang-1b098a.netlify.com/io/) that shows on webmention.io and in [the API-call](https://webmention.io/api/mentions?jsonp=window.JekyllWebmentionIO.processWebmentions&target[]=https://ecstatic-jang-1b098a.netlify.com/io/) from the source code. But how do I show these webmentions on my site? I've included the   {% webmentions %} tag below the blogpost but all I see is Liquid code with display:none in the devtools. What am I doing wrong and how can I fix this?

**Comment by aarongustafson** [comment]
Can you link me to your template? Your template should include the `post.url`:

```liquid
{% webmentions page.url %}
```

It also might help to see your config. You can also run `bundle exec jekyll build --trace` to see if any errors are thrown.

**Comment by aarongustafson** [comment]
@frankmeeuwsen Are you still having this issue?

**Comment by frankmeeuwsen** [comment]
I apologize for the radio silence. I haven't been able to work or debug on this for the last couple of weeks. I hope to do so in the near future and will keep you posted.

**Comment by aarongustafson** [comment]
👍🏻

**Comment by frankmeeuwsen** [comment]
Sorry again. I did some digging with fresh eyes and I saw some inconsistencies in the code and used test URLs. I changed some bits and pieces and tried the webmention testsuite again. This gives a success but nothing again is shown. Here are some URL's to (hopefully) relevant code:

- [Webmention report](https://webmention.io/ecstatic-jang-1b098a.netlify.com/webmention/budbXWrHc57YpmSmRwd4)
- [Blogpost on my testblog](https://ecstatic-jang-1b098a.netlify.com/io/)
- [Testblog repo](https://github.com/frankmeeuwsen/microblog/)
- [Webmentions include from my blog](https://github.com/frankmeeuwsen/microblog/blob/master/_includes/webmentions.html)
- [Webmention and pingback in the head](https://github.com/frankmeeuwsen/microblog/blob/master/_layouts/default.html#L14)
- [Screenshot from current situation on page without webmention](https://cl.ly/8b1bd15af5c4/Image%202018-12-27%20at%2010.04.29%20PM.png)

Hope this helps...

**Comment by aarongustafson** [comment]
Ok, so one (potential) issue I see is a mismatch in your config. [The URL you have is simply “/” which is not a valid URL and does not match your domain](https://github.com/frankmeeuwsen/microblog/blob/master/_config.yml#L20). To see if this is the culprit, I’d add the JS code to your page because it will inject the reference URL to webmention.io in the markup as a `script`. It’s worth noting that if I query Webmention.io for one of your pages ([like this one](https://webmention.io/api/mentions?jsonp=window.JekyllWebmentionIO.processWebmentions&target%5B%5D=https://ecstatic-jang-1b098a.netlify.com/io/)) I get results. Currently [no webmentions have been gathered](https://github.com/frankmeeuwsen/microblog/blob/master/.jekyll-cache/webmention_io_received.yml), which is why I think this might be the case.

Note: You may also want to check [your username in the config](https://github.com/frankmeeuwsen/microblog/blob/master/_config.yml#L26).

**Comment by frankmeeuwsen** [comment]
Thanks for the help. As this is a testserver to see how webmentions work with my Jekyll installation, some configuration might be off indeed, thanks for the pointers. I'll have another look at the different parts and will report back to you.
