### ISSUE TITLE
Add documentation about custom templates

### ISSUE THREAD

**Issue by aarongustafson** [aarongustafson/jekyll-webmention_io#125]
Include the bit about the count always being a string because of Liquid.

**Comment by leecalvink** [comment]
Hi Aaron.

The existing template documentation is a little unclear. For instance, are the elements listed in the Default template info ones you must use in your own templates? Is it possible for example to use a section tag, rather than a div for the overall container? 

Also will the generated output behave and stick strictly to custom templates or does it spit out elements that you decide not to include?

**Comment by aarongustafson** [comment]
If you make a custom template, it will only output what you want it to. You can use the ones baked in as a starting point if you like. Only the variables matter and any unused ones will be omitted. You have complete control. You can also view the raw webmentions cached by the plug-in and reference any of the available dates (including the raw/unsynthesized webmention).

**Comment by leecalvink** [comment]
Sounds perfect, thank you.

**Comment by kslstn** [comment]
Could anyone tell me how custom templates are supposed to be set up? What I believe I should do is:
1. Set up the config so the plugin knows what template to use for what include, [as already described in the docs](https://aarongustafson.github.io/jekyll-webmention_io/configuration#exhaustive-example).
2. Add liquid files for each include, f.e. `_includes/webmentions/likes.html` for HTML that's inserted where `{% webmention_likes %}` occurs in a template.

What's unclear to me is what properties are available in the includes. Normally I'd do something like `{{ include.property }}`, but how do I find out which are available?

Happy to update the docs once I understand this myself :)
