### ISSUE TITLE
ERROR `/{{ webmention.author.photo }}' not found.

### ISSUE THREAD

**Issue by xplosionmind** [aarongustafson/jekyll-webmention_io#159]
When serving my website, when opening almost any page, I get this in the terminal:

```
ERROR `/{{ webmention.author.photo }}' not found.
```

I have no idea of the source of the error. Should I add a link to my profile picture in `_config.yml`? How and where?

**Comment by fancypantalons** [comment]
This looks like a bug in Firefox 94.

The way the client-side javascript works, there's a custom tag "<template>" tag that's created containing a Liquid template that's evaluated client-side to render webmentions dynamically.

The contents of that tag *should* be completely ignored by the browser, and running a quick test in Chromium, I'm seeing that.  The same is true in Firefox 92.

But in Firefox 94, it appears it's *not* behaving the same way, attempting to do a fetch for the image URL used in that template (which contains the string you've identified).

Gotta give Firefox credit, this is quite the regression... makes me wonder how many other folks will be bitten by this, since it'll likely affect any use of custom tags...

**Comment by xplosionmind** [comment]
Indeed I can’t.

Let’s hope this problem gets fixed in Firefox!

**Comment by erikw** [comment]
I can confirm that I see this in Firefox `94` but not in Chrome `96`.
