### ISSUE TITLE
`html_proofer: true` does not result in `data-proofer-ignore` attribute on `webmentions page.url` output

### ISSUE THREAD

**Issue by l0b0** [aarongustafson/jekyll-webmention_io#172]
I'm not sure if I've understood the [documentation](https://aarongustafson.github.io/jekyll-webmention_io/configuration). I'd expect that with

```
webmentions:
  html_proofer: true
```

in `_config.yml` and `{% webmentions page.url %}` in `_layouts/post.html`, the top-level `<div class="webmentions">` should also have a `data-proofer-ignore` attribute, but that's not happening.

[Workaround](https://gitlab.com/engmark/engmark.gitlab.io/-/merge_requests/277/diffs?commit_id=1679896664c9d62dfb549c2edb4bef147cd69371): Manually add `<div data-proofer-ignore>` around `{% webmentions page.url %}`.

**Comment by fancypantalons** [comment]
The purpose of the `html_proofer` configuration setting is to handle the `<template>` tags that are embedded in the HTML that are used to dynamically generate content when pulling webmentions client-side (if you view the source of a rendered page or post you can see what they look like).

The configuration setting causes the `data-proofer-ignore` attribute to be applied to the top-level `<template>` tags embedded in the page, which, according to the documentation, should cause that tag and it's contents to be ignored:

https://github.com/gjtorikian/html-proofer

So if you're referring to the `<div class="webmentions">` present nested in the `<template>` tags, then the inclusion of the attribute in that top-level element should cover them.

If you're referring to `<div>` elements present outside those `<template>` tags, then I believe the `data-proofer-ignore` attribute is not being included by design, since those are real, rendered tags on the page and should be checked.

Can you describe the issue you're experiencing with the current behaviour?

**Comment by l0b0** [comment]
I'm using

```
webmentions:
  html_proofer: true
```

and `{% webmentions page.url %}`, but there's no `data-proofer-ignore` attribute in the resulting markup. This results in webmentions being checked by `htmlproofer`, causing my CI pipeline to fail.

**Comment by fancypantalons** [comment]
Ahh, okay, so if I'm understanding you right, during the build your site is pulling down webmention content and embedding it, and that content itself is causing the proofer to fail.

That issue is certainly not what that setting was originally meant to protect against, but as an enhancement it sounds like good optional behaviour (I'm not 100% sure everyone would want to publish a fully rendered site that doesn't pass the proofer--that's kinda the point--so I wouldn't want to make it mandatory).

Perhaps adding a new config like:

```
webmentions:
  html_proofer_ignore: [none/templates/all]
```

With the default being `none`, the current setting, when set to true, mapped to `templates`, and the behaviour you're looking for would be equivalent to `all`.

Would that do the job?

**Comment by l0b0** [comment]
Hi @fancypantalons, I've clearly misunderstood the option in that case. A new option would be useful to avoid false positives from third-party HTML.

**Comment by fancypantalons** [comment]
Alright, I've implemented the change I proposed above.  Note, if you've customized your webmention templates, you'll have to make some changes to them so the `data-proofer-ignore` attribute is included (you can look at the packed in templates to see how it's done).

**Comment by l0b0** [comment]
AFAICT `html_proofer_ignore: all` has identical behaviour to `html_proofer_ignore: templates`. Is this intentional? Also, what's the semantics of the difference, if any?

**Comment by fancypantalons** [comment]
No, there should be a difference.

Specifically, in the rendered webmentions that are embedded in the page (i.e. *not* the ones loaded dynamically if you're using the JS to load them on-the-fly), the top-level div containing the webmentions will include the `data-proofer-ignore` attribute.

Note, it's only applied to that top-level element since the proofer gem will ignore all sub-elements of elements that have that attribute (or, at least, that's my understanding).

Now, the way this is achieve is by passing the `html_proofer_ignore` setting into the webmention templates themselves, and then the templates contain the necessary logic.

Critically, if you've customized the templates at all (that is, configured the `templates` settings hash to point to your own custom templates), then the changes won't be applied.  You'll need to update your templates to include the relevant logic.

In hindsight, this feature is actually a bit unnecessary.  In your layout files where you use the webmention tags, you can just wrap the tag in a div with the necessary attribute.  But, eh, it's convenient.
