### ISSUE TITLE
Optimize JS tag by generating the `template`markup once?

### ISSUE THREAD

**Issue by aarongustafson** [aarongustafson/jekyll-webmention_io#99]
@ashmaroli As you know a lot more about the innards of Jekyll than I do, you can probably shed some light here.

Right now the `webmention_js` tag [assembles template contents each time it is rendered](https://github.com/aarongustafson/jekyll-webmention_io/blob/master/lib/jekyll/tags/webmentions_js.rb#L37-L44). The template names are referenced in the `WebmentionIO` object and then rendered by calling [`Jekyll::WebmentionIO.get_template_contents()`](https://github.com/aarongustafson/jekyll-webmention_io/blob/master/lib/jekyll/webmention_io.rb#L238-L247) which is a disk read every time. Would it make more sense (since the rendering is the same each time the tag is rendered) to temporarily—for the lifetime of `build`—to cache the result of the tag output the first time the tag is rendered and then respond with that if it exists?

Additionally, since other code calls this too, would it make sense to cache each template file’s contents when `Jekyll::WebmentionIO.get_template_contents()` is called?

What would be the best/most Jekyll way to do that?

**Comment by ashmaroli** [comment]
I hadn't looked into the source-code for `webmention_js` tag till yesterday when I thought of using Cucumber to add some test coverage..
And now, with this ticket, I took a closer look at the workings of the tag:
**The entire `:render` method for the tag can be cached** since the method's dependencies are only the site-configuration.. :sweat_smile: 

I'll open a PR to address it..

**Comment by aarongustafson** [comment]
Amazing! thank you so much! once I understand the pattern, I'll look for other places to optimize the output.
